# Generated by Django 5.1.4 on 2025-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(default='Cebu', max_length=255),
            preserve_default=False,
        ),
    ]
