# Generated by Django 5.1.6 on 2025-02-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_to_inventory_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_on_arrival', models.CharField(choices=[('very good', 'Very Good'), ('good', 'Good'), ('bad', 'Bad'), ('unknown', 'Unknown')], max_length=50)),
                ('expected_to_last_until', models.DateField()),
                ('left_in_stock', models.PositiveIntegerField(default=0)),
                ('initial_stock', models.PositiveIntegerField(default=0)),
                ('is_spoiled', models.BooleanField(default=False)),
                ('purchased_from', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_produce', to='batches.batch')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_entries', to='produce.produce')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('very good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('bad', 'Bad'), ('unknown', 'Unknown')], max_length=50)),
                ('checked_on', models.DateField(auto_now_add=True)),
                ('batch_produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='batches.batchproduce')),
            ],
        ),
        migrations.AddConstraint(
            model_name='batchproduce',
            constraint=models.UniqueConstraint(fields=('batch', 'produce'), name='unique_batch_produce'),
        ),
    ]
